In [3]:
import numpy as np

In [4]:
arr = np.array([1,2,3,4])
arr

array([1, 2, 3, 4])

In [8]:
a = [1,2,3,4,5]
a

[1, 2, 3, 4, 5]

In [9]:
np.array(a)

array([1, 2, 3, 4, 5])

In [10]:
l = [[1,2,3], [4,5,6], [7,8,9]]
l

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [11]:
np.array(l)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [18]:
arr = np.zeros((6,6))
arr

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [19]:
arr = np.ones((6,6))
arr

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

In [20]:
arr = np.linspace(1,7,6)
arr

array([1. , 2.2, 3.4, 4.6, 5.8, 7. ])

In [22]:
np.random.rand(10)

array([0.56175828, 0.88533966, 0.40478784, 0.47935488, 0.47774941,
       0.18907714, 0.82178324, 0.62270216, 0.49402376, 0.23379683])

In [24]:
np.random.randn(10)

array([-1.64678747,  0.46286876, -0.17856509, -1.10775474, -0.61370763,
       -2.85518367, -0.10666682, -1.02611641,  1.5660804 , -0.53892639])

In [25]:
np.random.randint(12,22,5)

array([17, 20, 12, 13, 19], dtype=int32)

In [ ]:
array attribute

In [26]:
arr = np.array([[1,2,3], [4,5,6], [7,8,9]])
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [28]:
arr.shape

(3, 3)

In [29]:
arr.size

9

In [30]:
arr.dtype

dtype('int64')

In [ ]:
arry method

In [31]:
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [33]:
arr.min()

np.int64(1)

In [34]:
arr.max()

np.int64(9)

In [35]:
arr.sum()

np.int64(45)

In [36]:
np.sum(arr,axis = 1)

array([ 6, 15, 24])

In [37]:
arr.mean()

np.float64(5.0)

In [38]:
arr.std()

np.float64(2.581988897471611)

In [39]:
arr.argmax()

np.int64(8)

In [40]:
arr.argmin()

np.int64(0)

In [ ]:
RESHAPI(NG AND REARANGING

In [43]:
arr = np.arange(1,31)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30])

In [45]:
arr.reshape(6,5)

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])

In [46]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30])

In [ ]:
NUMPY INDEXING AS SLICING OF VECTORS

In [48]:
arr = np.arange(11,21)
arr

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [49]:
arr[9]

np.int64(20)

In [50]:
arr[1:5]

array([12, 13, 14, 15])

In [47]:
NUMPY INDEXING AS SLICING OF MATRIX

SyntaxError: invalid syntax (530456053.py, line 1)

In [51]:
arr = np.arange(1,31).reshape(6,5)
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])

In [54]:
arr[5]

array([26, 27, 28, 29, 30])

In [55]:
arr[0,0]

np.int64(1)

In [59]:
arr[0,4]

np.int64(5)

In [60]:
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])

In [61]:
arr[0:2,1:3]

array([[2, 3],
       [7, 8]])

In [62]:
arr[3:, 3:]

array([[19, 20],
       [24, 25],
       [29, 30]])

In [63]:
arr[:,4]

array([ 5, 10, 15, 20, 25, 30])

In [68]:
B

SyntaxError: invalid syntax (4032398186.py, line 1)

In [65]:
arr= np.arange(10,21)
arr

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [66]:
boolindex = arr % 2 == 0
boolindex

array([ True, False,  True, False,  True, False,  True, False,  True,
       False,  True])

In [67]:
arr = arr[boolindex]
arr

array([10, 12, 14, 16, 18, 20])

# 

# NUMPY OPRRATIONS

In [69]:
import numpy as np

# ARTHIMATIC OPERATON

In [71]:
a1 = np.array([1,2,3,4,5])
a2 = np.array([6,7,8,9,10])

In [72]:
a1 + a2

array([ 7,  9, 11, 13, 15])

In [73]:
a1 - a2

array([-5, -5, -5, -5, -5])

In [74]:
a1 / a2

array([0.16666667, 0.28571429, 0.375     , 0.44444444, 0.5       ])

In [76]:
a1 ** a2

array([      1,     128,    6561,  262144, 9765625])

# boardcasting

In [79]:
l = [10,20,30,40]
arr= np.array(l)

In [80]:
arr + 10

array([20, 30, 40, 50])

# deep and shallow copy 

In [83]:
a = np.arange(1,15)
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [86]:
slice = a[:5]
slice 

array([1, 2, 3, 4, 5])

In [87]:
slice + 10

array([11, 12, 13, 14, 15])

In [88]:
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

# matrix operatin

In [89]:
a = np.array([[1,2], [3,4]])
b = np.array([[5,6], [7,8]])

In [90]:
a

array([[1, 2],
       [3, 4]])

In [91]:
a @ b

array([[19, 22],
       [43, 50]])

In [94]:
a.T

array([[1, 3],
       [2, 4]])

# advance sarray manipulation

# stacking array

In [97]:
a = np.array([[1,2], [3,4]])
b = np.array([[5,6], [7,8]])

In [99]:
np.vstack((a,b))

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [100]:
np.hstack((a,b))

array([[1, 2, 5, 6],
       [3, 4, 7, 8]])

In [101]:
np.column_stack((a,b))

array([[1, 2, 5, 6],
       [3, 4, 7, 8]])

# splitting array

In [103]:
c = np.arange(16).reshape(4,4)
c

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [106]:
np.hsplit(c,2)

[array([[ 0,  1],
        [ 4,  5],
        [ 8,  9],
        [12, 13]]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11],
        [14, 15]])]

In [107]:
np.vsplit(c,2)

[array([[0, 1, 2, 3],
        [4, 5, 6, 7]]),
 array([[ 8,  9, 10, 11],
        [12, 13, 14, 15]])]

# EREXCISE

In [109]:
import numpy as np

# Valid Sudoku

In [111]:
s = np.array([
    [5, 3, 4, 6, 7, 8, 9, 1, 2],
    [6, 7, 2, 1, 9, 5, 3, 4, 8],
    [1, 9, 8, 3, 4, 2, 5, 6, 7],
    
    [8, 5, 9, 7, 6, 1, 4, 2, 3],
    [4, 2, 6, 8, 5, 3, 7, 9, 1],
    [7, 1, 3, 9, 2, 4, 8, 5, 6],
    
    [9, 6, 1, 5, 3, 7, 2, 8, 4],
    [2, 8, 7, 4, 1, 9, 6, 3, 5],
    [3, 4, 5, 2, 8, 6, 1, 7, 9]
])

In [116]:
b = np.sum(s,axis = 1)
b == 45

array([ True,  True,  True,  True,  True,  True,  True,  True,  True])

In [118]:
s[0:3,0:3]

array([[5, 3, 4],
       [6, 7, 2],
       [1, 9, 8]])

# General Questions

In [165]:
import numpy as np

# Columns: [Age, Math Marks, Science Marks]
data = np.array([
    [18, 85, 78],   # Student 1
    [19, 92, 88],   # Student 2
    [17, 76, 95],   # Student 3
    [18, 65, 70],   # Student 4
    [20, 90, 85]    # Student 5
])

In [123]:
#Get the shape of the matrix.

data.shape

(5, 3)

In [126]:
#Find the average age of students.

np.mean(data[:,0])

np.float64(18.4)

In [129]:
#Extract Math marks of all students.

data[:,1]

array([85, 92, 76, 65, 90])

In [133]:
#Find the highest Science mark.

np.max(data[:,2])

np.int64(95)

In [135]:
#Get details of the student who scored more than 90 in Math.

data[data[:,1] > 90]

array([[19, 92, 88]])

In [138]:
#Increase Math marks of all students by 5.

data[:,1] + 5

array([90, 97, 81, 70, 95])

In [143]:
#Find how many students are younger than 19.

len(data[data[:,0] < 19])

3

In [150]:
#Calculate the average marks ineach subject (column wisae -mean)

np.mean(data[:,1:],axis = 0)

array([81.6, 83.2])

In [156]:
#Get data of students who scored at least 80 in both subjects.

data[(data[:,1] >= 80) & (data[:,2] >= 80)]

array([[19, 92, 88],
       [20, 90, 85]])

In [166]:
#Replace all Science marks < 75 with 0.

data[:,2][data[:,2] < 75] = 0
data


array([[18, 85, 78],
       [19, 92, 88],
       [17, 76, 95],
       [18, 65,  0],
       [20, 90, 85]])

# DONE